name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Lint Ruby code
        run: bundle exec rubocop
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libglfw3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec

  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - run: brew install glfw
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      MITTSU_LIBGLFW_PATH: c:\projects\mittsu\glfw-3.4.bin.WIN32\lib-mingw
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - run: .\install-glfw.ps1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
